name: GitHub-Profile-3D-Contrib

permissions:
  contents: write
  pages: write

on:
  schedule: # 00:00 JST == 15:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: '{"theme":"dark-pink","colorPattern1":"#0D1117","colorPattern2":"#121723","colorPattern3":"#1e293b","colorPattern4":"#6366f1","colorPattern5":"#F724A9","backgroundColor":"#0D1117"}'
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contribution profile"
          git push
